/* 
    Items ONY MC
    (12, '', '', ''),
    1:Ony,2:Luci,3:Magma,4:Gehe,5:Garr,6:Shaz,7:Ged,8:Sulf,9:Gole,10:Majo,11:Ragi,12:Trash
    1:Priest,2:Mage,3:Warlock,4:Rogue,5:Druid,6:Hunter,7:Shaman,8:Warri,9:Pala
            */

INSERT INTO [schmond].[dbo].[Item] ([ItemName], [ItemNameEN], [FK_ItemTypeId]) VALUES
    ('', 'Netherwind Crown', 10),
    ('', 'Halo of Transcendence', 10),
    ('', 'Nemesis Skullcap', 10),
    ('', 'Stormrage Cover', 11),
    ('', 'Bloodfang Hood', 11),
    ('', 'Dragonstalker''s Helm', 12),
    ('', 'Helmet of Ten Storms', 12),
    ('', 'Helm of Wrath', 13),
    ('', 'Judgement Crown', 13),
    ('', 'Mature Black Dragon Sinew', 1),
    ('', 'Sapphiron Drape', 40),
    ('', 'Deathbringer', 150),
    ('', 'Vis''kag the Bloodletter', 154),
    ('', 'Ancient Cornerstone Grimoire', 170),
    ('', 'Ring of Binding', 130),
    ('', 'Shard of the Scale', 140),
    ('', 'Eskhandar''s Collar', 20),
    ('', 'Head of Onyxia', 1)

INSERT INTO [schmond].[dbo].[Item] ([ItemName], [ItemNameEN], [FK_ItemTypeId]) VALUES    
    ('', 'Arcanist Boots', ''),
    ('', 'Felheart Gloves', ''),
    ('', 'Cenarion Boots', ''),
    ('', 'Earthfury Boots', ''),
    ('', 'Gauntlets of Might', ''),
    ('', 'Lawbringer Boots', ''),
    ('', 'Manastorm Leggings', ''),
    ('', 'Robe of Volatile Power', ''),
    ('', 'Wristguards of Stability', ''),
    ('', 'Salamander Scale Pants', ''),
    ('', 'Helm of the Lifegiver', ''),
    ('', 'Flamewaker Legplates', ''),
    ('', 'Sorcerous Dagger', ''),
    ('', 'Crimson Shocker', ''),
    ('', 'Heavy Dark Iron Ring', ''),
    ('', 'Ring of Spell Power', ''),
    ('', 'Choker of Enlightenment', '')

INSERT INTO [schmond].[dbo].[Item] ([ItemName], [ItemNameEN], [FK_ItemTypeId]) VALUES   
    ('', 'Arcanist Leggings', ''),
    ('', 'Pants of Prophecy', ''),
    ('', 'Felheart Pants', ''),
    ('', 'Nightslayer Pants', ''),
    ('', 'Giantstalker''s Leggings', ''),
    ('', 'Cenarion Leggings', ''),
    ('', 'Earthfury Legguards', ''),
    ('', 'Lawbringer Legplates', ''),
    ('', 'Legplates of Might', ''),
    ('', 'Mana Igniting Cord', ''),
    ('', 'Aged Core Leather Gloves', ''),
    ('', 'Deep Earth Spaulders', ''),
    ('', 'Sabatons of the Flamewalker', ''),
    ('', 'Flameguard Gauntlets', ''),
    ('', 'Magma Tempered Boots', ''),
    ('', 'Flamewaker Legplates', ''),
    ('', 'Earthshaker', ''),
    ('', 'Obsidian Edged Blade', ''),
    ('', 'Eskhandar''s Right Claw', ''),
    ('', 'Striker''s Mark', ''),
    ('', 'Fire Runed Grimoire', ''),
    ('', 'Medallion of Steadfast Might', ''),
    ('', 'Quick Strike Ring', ''),
    ('', 'Talisman of Ephemeral Power', '')
    
INSERT INTO [schmond].[dbo].[Item] ([ItemName], [ItemNameEN], [FK_ItemTypeId]) VALUES
    ('', 'Gloves of Prophecy', ''),
    ('', 'Nightslayer Gloves', ''),
    ('', 'Giantstalker''s Boots', ''),
    ('', 'Earthfury Gauntlets', ''),
    ('', 'Sabatons of Might', ''),
    ('', 'Lawbringer Gauntlets', ''),
    ('', 'Manastorm Leggings', ''),
    ('', 'Robe of Volatile Power', ''),
    ('', 'Salamander Scale Pants', ''),
    ('', 'Wristguards of Stability', ''),
    ('', 'Helm of the Lifegiver', ''),
    ('', 'Flamewaker Legplates', ''),
    ('', 'Sorcerous Dagger', ''),
    ('', 'Crimson Shocker', ''),
    ('', 'Heavy Dark Iron Ring', ''),
    ('', 'Ring of Spell Power', '')

INSERT INTO [schmond].[dbo].[Item] ([ItemName], [ItemNameEN], [FK_ItemTypeId]) VALUES
    ('', 'Arcanist Crown', ''),
    ('', 'Circlet of Prophecy', ''),
    ('', 'Felheart Horns', ''),
    ('', 'Giantstalker''s Helmet', ''),
    ('', 'Cenarion Helm', ''),
    ('', 'Nightslayer Cover', ''),
    ('', 'Earthfury Helmet', ''),
    ('', 'Helm of Might', ''),
    ('', 'Lawbringer Helm', ''),
    ('', 'Bindings of the Windseeker', ''),
    ('', 'Mana Igniting Cord', ''),
    ('', 'Aged Core Leather Gloves', ''),
    ('', 'Sabatons of the Flamewalker', ''),
    ('', 'Deep Earth Spaulders', ''),
    ('', 'Flameguard Gauntlets', ''),
    ('', 'Magma Tempered Boots', ''),
    ('', 'Flamewaker Legplates', ''),
    ('', 'Obsidian Edged Blade', ''),
    ('', 'Brutality Blade', ''),
    ('', 'Gutgore Ripper', ''),
    ('', 'Aurastone Hammer', ''),
    ('', 'Drillborer Disk', ''),
    ('', 'Fire Runed Grimoire', ''),
    ('', 'Quick Strike Ring', ''),
    ('', 'Talisman of Ephemeral Power', '')
    
INSERT INTO [schmond].[dbo].[Item] ([ItemName], [ItemNameEN], [FK_ItemTypeId]) VALUES
    ('', 'Arcanist Gloves', ''),
    ('', 'Felheart Slippers', ''),
    ('', 'Boots of Prophecy', ''),
    ('', 'Cenarion Gloves', ''),
    ('', 'Giantstalker''s Gloves', ''),
    ('', 'Nightslayer Boots', ''),
    ('', 'Robe of Volatile Power', ''),
    ('', 'Manastorm Leggings', ''),
    ('', 'Salamander Scale Pants', ''),
    ('', 'Wristguards of Stability', ''),
    ('', 'Helm of the Lifegiver', ''),
    ('', 'Flamewaker Legplates', ''),
    ('', 'Sorcerous Dagger', ''),
    ('', 'Crimson Shocker', ''),
    ('', 'Heavy Dark Iron Ring', ''),
    ('', 'Ring of Spell Power', '')
    
INSERT INTO [schmond].[dbo].[Item] ([ItemName], [ItemNameEN], [FK_ItemTypeId]) VALUES
    ('', 'Arcanist Mantle', ''),
    ('', 'Felheart Shoulder Pads', ''),
    ('', 'Cenarion Spaulders', ''),
    ('', 'Lawbringer Spaulders', ''),
    ('', 'Earthfury Epaulets', ''),
    ('', 'Bindings of the Windseeker', ''),
    ('', 'Mana Igniting Cord', ''),
    ('', 'Aged Core Leather Gloves', ''),
    ('', 'Sabatons of the Flamewalker', ''),
    ('', 'Deep Earth Spaulders', ''),
    ('', 'Flameguard Gauntlets', ''),
    ('', 'Magma Tempered Boots', ''),
    ('', 'Flamewaker Legplates', ''),
    ('', 'Obsidian Edged Blade', ''),
    ('', 'Fire Runed Grimoire', ''),
    ('', 'Talisman of Ephemeral Power', ''),
    ('', 'Seal of the Archmagus', ''),
    ('', 'Quick Strike Ring', '')
    
INSERT INTO [schmond].[dbo].[Item] ([ItemName], [ItemNameEN], [FK_ItemTypeId]) VALUES
    ('', 'Mantle of Prophecy', ''),
    ('', 'Nightslayer Shoulder Pads', ''),
    ('', 'Giantstalker''s Epaulets', ''),
    ('', 'Pauldrons of Might', ''),
    ('', 'Robe of Volatile Power', ''),
    ('', 'Manastorm Leggings', ''),
    ('', 'Wristguards of Stability', ''),
    ('', 'Salamander Scale Pants', ''),
    ('', 'Helm of the Lifegiver', ''),
    ('', 'Flamewaker Legplates', ''),
    ('', 'Crimson Shocker', ''),
    ('', 'Shadowstrike', ''),
    ('', 'Sorcerous Dagger', ''),
    ('', 'Heavy Dark Iron Ring', ''),
    ('', 'Ring of Spell Power', '')
    
INSERT INTO [schmond].[dbo].[Item] ([ItemName], [ItemNameEN], [FK_ItemTypeId]) VALUES
    ('', 'Arcanist Robes', ''),
    ('', 'Robes of Prophecy', ''),
    ('', 'Felheart Robes', ''),
    ('', 'Nightslayer Chestpiece', ''),
    ('', 'Cenarion Vestments', ''),
    ('', 'Giantstalker''s Breastplate', ''),
    ('', 'Earthfury Vestments', ''),
    ('', 'Breastplate of Might', ''),
    ('', 'Lawbringer Chestguard', ''),
    ('', 'Sulfuron Ingot', ''),
    ('', 'Mana Igniting Cord', ''),
    ('', 'Aged Core Leather Gloves', ''),
    ('', 'Sabatons of the Flamewalker', ''),
    ('', 'Deep Earth Spaulders', ''),
    ('', 'Flameguard Gauntlets', ''),
    ('', 'Magma Tempered Boots', ''),
    ('', 'Flamewaker Legplates', ''),
    ('', 'Obsidian Edged Blade', ''),
    ('', 'Azuresong Mageblade', ''),
    ('', 'Staff of Dominance', ''),
    ('', 'Blastershot Launcher', ''),
    ('', 'Quick Strike Ring', ''),
    ('', 'Fire Runed Grimoire', ''),
    ('', 'Talisman of Ephemeral Power', '')
    
INSERT INTO [schmond].[dbo].[Item] ([ItemName], [ItemNameEN], [FK_ItemTypeId]) VALUES
    ('', 'Fireproof Cloak', ''),
    ('', 'Gloves of the Hypnotic Flame', ''),
    ('', 'Sash of Whispered Secrets', ''),
    ('', 'Fireguard Shoulders', ''),
    ('', 'Wild Growth Spaulders', ''),
    ('', 'Wristguards of True Flight', ''),
    ('', 'Core Forged Greaves', ''),
    ( '', 'Core Hound Tooth', ''),
    ('', 'Finkle''s Lava Dredger', ''),
    ('', 'Cauterizing Band', ''),
    ('', 'Ancient Petrified Leaf', ''),
    ('', 'The Eye of Divinity', '')
    
INSERT INTO [schmond].[dbo].[Item] ([ItemName], [ItemNameEN], [FK_ItemTypeId]) VALUES
    ('', 'Netherwind Pants', ''),
    ('', 'Leggings of Transcendence', ''),
    ('', 'Nemesis Leggings', ''),
    ('', 'Bloodfang Pants', ''),
    ('', 'Stormrage Legguards', ''),
    ('', 'Dragonstalker''s Legguards', ''),
    ('', 'Legplates of Ten Storms', ''),
    ('', 'Legplates of Wrath', ''),
    ('', 'Judgement Legplates', ''),
    ('', 'Eye of Sulfuras', ''),
    ('', 'Cloak of the Shrouded Mists', ''),
    ('', 'Dragon''s Blood Cape', ''),
    ('', 'Crown of Destruction', ''),
    ('', 'Onslaught Girdle', ''),
    ('', 'Spinal Reaper', ''),
    ('', 'Bonereaver''s Edge', ''),
    ('', 'Perdition''s Blade', ''),
    ('', 'Malistar''s Defender', ''),
    ('', 'Essence of the Pure Flame', ''),
    ('', 'Choker of the Fire Lord', ''),
    ('', 'Band of Sulfuras', ''),
    ('', 'Band of Accuria', ''),
    ('', 'Shard of the Flame', '')
    
INSERT INTO [schmond].[dbo].[Item] ([ItemName], [ItemNameEN], [FK_ItemTypeId]) VALUES
    ('', 'Arcanist Belt', ''),
    ('', 'Girdle of Prophecy', ''),
    ('', 'Felheart Belt', ''),
    ('', 'Nightslayer Belt', ''),
    ('', 'Cenarion Belt', ''),
    ('', 'Giantstalker''s Belt', ''),
    ('', 'Earthfury Belt', ''),
    ('', 'Belt of Might', ''),
    ('', 'Lawbringer Belt', ''),
    ('', 'Arcanist Bindings', ''),
    ('', 'Vambraces of Prophecy', ''),
    ('', 'Felheart Bracers', ''),
    ('', 'Nightslayer Bracelets', ''),
    ('', 'Cenarion Bracers', ''),
    ('', 'Giantstalker''s Bracers', ''),
    ('', 'Earthfury Bracers', ''),
    ('', 'Bracers of Might', ''),
    ('', 'Lawbringer Bracers', '')

